Coordinate
===========

CartGrid3D
-----------
.. c:var:: Variable

    :param scalar coarse_dx: 3D Cartesian grid spacings in x direction
    :param scalar coarse_dy: 3D Cartesian grid spacings in y direction
    :param scalar coarse_dz: 3D Cartesian grid spacings in z direction
    :param gf x: 3D Cartesian grid coordinates x
    :param gf y: 3D Cartesian grid coordinates y
    :param gf z: 3D Cartesian grid coordinates z
    :param gf r: 3D Cartesian grid coordinates r