Tracker
========

.. code-block:: c

    position_x[n] = sf_centroid_x[sn]

Hydro_Analysis
---------------
Variable
^^^^^^^^^
.. c:var:: Hydro_Analysis_rho_max 

    value of the maximum of rho

.. c:var:: Hydro_Analysis_rho_max_loc[3]

    coordinate location of the maximum of rho

.. c:var:: Hydro_Analysis_rho_center_volume_weighted[3]

    coordinate location of the volume weightes center of mass

.. c:var:: Hydro_Analysis_core_rho_centroid[3]

    coordinate location of the centroid of rho*x in the core region

.. c:var:: Hydro_Analysis_rho_max_origin_distance

    proper distance between the maximum of the density and the origin (along a straight coordinate line)

function
^^^^^^^^^